import Head from 'next/head'
import Image from 'next/image'
import Main from '../components/Main';
import Top from '../components/Top';

export default function Home() {
  return (
    <div className="antialiased bg-[#c5e4e7] ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Top />
        <Main/>
      </main>

      <footer></footer>
    </div>
  );
}
